# Generated by Django 4.2.2 on 2023-08-01 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='title',
            new_name='product_name',
        ),
        migrations.AddField(
            model_name='product',
            name='product_name_slug',
            field=models.SlugField(default='product-2'),
            preserve_default=False,
        ),
    ]
