# Generated by Django 4.2.2 on 2023-08-01 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_title_product_product_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='votes_total',
        ),
    ]
